version: 0.1

phases:
  build:
    commands:
      - go get -d -v
      - export GOBIN="${CODEBUILD_SRC_DIR}/output" && go build *.go && ls -al && ls -al output 

artifacts:
  files:
    - '**/*'
  base-directory: 'output'
