version: 0.1

phases:
  build:
    commands:
      - go get -d -v
      - ls -al
      # Build src binary
      - go build 
      - ls -al
      # Build main binary
      - go build *.go
      - ls -al
      # Change output location doesn't work?
      - mkdir output && export GOBIN="${CODEBUILD_SRC_DIR}/output" && go build
      - ls -alR ./output

artifacts:
  files:
    - main
    - src
    - 'output/**/*'
